#!/usr/bin/env bash

# We need this so we can alter the state of the parent shell, this acts as a
# wrapper around the underlying script.
dirstack() {
  case $1 in
    jump)
      if dirstack_driver peek ; then
        cd $(dirstack_driver peek)
      fi
    ;;
    pop)
      dirstack empty? && dirstack fail 1 ">>Empty Stack<<"
      dirstack jump && dirstack burn
    ;;
    *) dirstack_driver $@ ;;
  esac
}
