#!/usr/bin/env bash

# convienent clipboard command
if exists xclip ; then
  alias clipboard='xclip -selection clipboard -in'
fi

# bake in sudo for aura/pacman depending on whats installed
alias pacman="sudo pacman --noconfirm"

if exists aura ; then
  alias pacman="sudo aura --noconfirm"
elif exists yaourt ; then
  alias pacman="sudo yaourt --noconfirm"
fi

# set up pbcopy/pbpaste for an X environment
if exists xsel ; then
  alias pbcopy='xsel --clipboard --input'
  alias pbpaste='xsel --clipboard --output'
fi
